[package]
name = "axum_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "*"
surreal_db = { version = "0.1.0", path = "../surreal_db" }
tokio = { version = "1", features = ["full"] }
